name: Deploy VitePress site to Tencent Cloud COS

on:
  push:
    branches: [main]

  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      # 记录开始时间
      - name: Record start time
        run: echo "START_TIME=$(date +%s)" >> $GITHUB_ENV

      # 拉取代码
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # 设置 pnpm（如果你用 npm/yarn 可以改掉）
      - uses: pnpm/action-setup@v3
        with:
          version: 9

      # 设置 Node
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: pnpm

      - name: Setup pnpm cache
        uses: actions/cache@v4
        with:
          path: ~/.pnpm-store
          key: ${{ runner.os }}-pnpm-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-

      # 安装依赖
      - name: Install dependencies
        run: pnpm install --no-frozen-lockfile

      # 构建 VitePress（根据你的脚本改）
      - name: Build with VitePress
        run: pnpm build

      # 上传到腾讯云 COS
      - name: Deploy to COS
        uses: TencentCloud/cos-action@v1
        with:
          secret_id: ${{ secrets.TENCENT_SECRET_ID }}
          secret_key: ${{ secrets.TENCENT_SECRET_KEY }}
          cos_bucket: ${{ secrets.TENCENT_BUCKET }}
          cos_region: ${{ secrets.TENCENT_REGION }}
          local_path: dist
          remote_path: /
          clean: true

      # 成功通知 (卡片样式)
      - name: Notify Feishu (success)
        if: success()
        env:
          FEISHU_WEBHOOK: ${{ secrets.FEISHU_WEBHOOK }}
          FEISHU_SECRET: ${{ secrets.FEISHU_SECRET }}
          START_TIME: ${{ env.START_TIME }}
        run: |
          END_TIME=$(date +%s)
          DURATION=$((END_TIME - START_TIME))
          MINUTES=$((DURATION / 60))
          SECONDS=$((DURATION % 60))
          TIME_STR="${MINUTES}分${SECONDS}秒"

          # 用当前时间戳生成签名
          TIMESTAMP=$(date +%s)
          string_to_sign="${TIMESTAMP}\n${FEISHU_SECRET}"
          sign=$(echo -n "$string_to_sign" | openssl dgst -sha256 -hmac "$FEISHU_SECRET" -binary | base64 | tr -d '\n')

          # 发送飞书消息
          curl -X POST "${FEISHU_WEBHOOK}?timestamp=${TIMESTAMP}&sign=${sign}" \
            -H 'Content-Type: application/json' \
            -d "{
              \"msg_type\": \"interactive\",
              \"card\": {
                \"config\": {\"wide_screen_mode\": true},
                \"header\": {
                  \"title\": {\"tag\": \"plain_text\", \"content\": \"✅ youyou-notes 部署成功\"},
                  \"template\": \"green\"
                },
                \"elements\": [
                  {\"tag\": \"div\", \"text\": {\"tag\": \"lark_md\", \"content\": \"**部署分支：** \`${{ github.ref_name }}\`\n**部署时间：** $(date '+%Y-%m-%d %H:%M:%S')\n**运行耗时：** ${TIME_STR}\n**访问地址：** [点击访问](https://notes.qiuyouyou.cn)\"}},
                  {\"tag\": \"action\", \"actions\": [
                    {\"tag\": \"button\", \"text\": {\"tag\": \"plain_text\", \"content\": \"查看构建日志\"}, \"url\": \"${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}\", \"type\": \"primary\"}
                  ]}
                ]
              }
            }"

      # 失败通知 (卡片样式)
      - name: Notify Feishu (failure)
        if: failure()
        env:
          FEISHU_WEBHOOK: ${{ secrets.FEISHU_WEBHOOK }}
          FEISHU_SECRET: ${{ secrets.FEISHU_SECRET }}
          START_TIME: ${{ env.START_TIME }}
        run: |
          END_TIME=$(date +%s)
          DURATION=$((END_TIME - START_TIME))
          MINUTES=$((DURATION / 60))
          SECONDS=$((DURATION % 60))
          TIME_STR="${MINUTES}分${SECONDS}秒"

          # 用当前时间戳生成签名
          TIMESTAMP=$(date +%s)
          string_to_sign="${TIMESTAMP}\n${FEISHU_SECRET}"
          sign=$(echo -n "$string_to_sign" | openssl dgst -sha256 -hmac "$FEISHU_SECRET" -binary | base64 | tr -d '\n')

          # 发送飞书消息
          curl -X POST "${FEISHU_WEBHOOK}?timestamp=${TIMESTAMP}&sign=${sign}" \
            -H 'Content-Type: application/json' \
            -d "{
              \"msg_type\": \"interactive\",
              \"card\": {
                \"config\": {\"wide_screen_mode\": true},
                \"header\": {
                  \"title\": {\"tag\": \"plain_text\", \"content\": \"❌ youyou-notes 部署失败\"},
                  \"template\": \"red\"
                },
                \"elements\": [
                  {\"tag\": \"div\", \"text\": {\"tag\": \"lark_md\", \"content\": \"**部署分支：** \`${{ github.ref_name }}\`\n**部署时间：** $(date '+%Y-%m-%d %H:%M:%S')\n**运行耗时：** ${TIME_STR}\n**访问地址：** [点击访问](https://notes.qiuyouyou.cn)\"}},
                  {\"tag\": \"action\", \"actions\": [
                    {\"tag\": \"button\", \"text\": {\"tag\": \"plain_text\", \"content\": \"查看构建日志\"}, \"url\": \"${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}\", \"type\": \"danger\"}
                  ]}
                ]
              }
            }"
